package main

import (
	"crypto/sha512"
	"fmt"
	"io/ioutil"
	"os"
)

func main() {
	if len(os.Args) != 2 {
		fmt.Fprintf(
			os.Stderr,
			"error: bad usage.\n" +
			"usage: prog filename\n")
		os.Exit(1)
	}

	data, err := ioutil.ReadFile(os.Args[1])
	if err != nil {
		panic(err)
	}
	sum := sha512.Sum512(data)
	fmt.Print("# generated by program written with Golang\n")
	for _, s := range sum {
		fmt.Printf("%02x", s)
	}
	fmt.Printf("  %s\n", os.Args[1])
}
